[workspace]
members = ["day01", "day02"]
resolver = "2"

[workspace.package]
license = "MIT"

[workspace.dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
itertools = "0.13.0"
